### ISSUE TITLE
Child models document

### ISSUE THREAD

**Issue by MJHastings** [EE-modders/Empire-Earth-toolbox#1]
I uploaded Philla’s child model doc (more detailed information than the things I have said in here) to your repository, along with the images that it uses.

Please can you upload it when you have a chance.

It is in MJHastings folder.

**Comment by zocker-160** [comment]
changes approved and pushed, thanks for your work!

it is available here:

https://github.com/EE-modders/Empire-Earth-toolbox/wiki/Tutorial---Empire-Earth-Modification---Child-Parts

and under "Child Models" from the main TOC
